# Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:minerva} 
spring.datasource.username=${POSTGRES_USER:minerva} 
spring.datasource.password=${POSTGRES_PASSWORD} 
spring.jpa.hibernate.ddl-auto=validate 
spring.datasource.driver-class-name=org.postgresql.Driver