spring.application.name=api
spring.profiles.active=dev
# Configuracion de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:minerva}} 
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:minerva}} 
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}} 
spring.jpa.hibernate.ddl-auto=validate 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
spring.jackson.time-zone=UTC
jwt.secret=${JWT_SECRET:QmFja2VuZC1EZXZlbG9wbWVudC1TZWNyZXQtS2V5LTEyMzQ1Ng==}
