CREATE TABLE universidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE plantel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    id_universidad BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_plantel_universidad
        FOREIGN KEY (id_universidad) REFERENCES universidad (id)
);

CREATE TABLE persona (
    id VARCHAR(255) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    rol VARCHAR(50) NOT NULL,
    id_plantel BIGINT NOT NULL,
    CONSTRAINT fk_persona_plantel
        FOREIGN KEY (id_plantel) REFERENCES plantel (id)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    reestablecimiento BOOLEAN NOT NULL DEFAULT FALSE,
    id_persona VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT fk_usuarios_persona
        FOREIGN KEY (id_persona) REFERENCES persona (id)
);

CREATE TABLE plan_estudio (
    detalles VARCHAR(255) PRIMARY KEY
);

CREATE TABLE materia (
    id VARCHAR(255) PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    prefijo VARCHAR(255) NOT NULL,
    id_plan_estudio VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_materia_plan_estudio
        FOREIGN KEY (id_plan_estudio) REFERENCES plan_estudio (detalles)
);

CREATE TABLE unidad (
    id VARCHAR(255) PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    id_materia VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_unidad_materia
        FOREIGN KEY (id_materia) REFERENCES materia (id)
);

CREATE TABLE tema (
    id VARCHAR(255) PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    id_unidad VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_tema_unidad
        FOREIGN KEY (id_unidad) REFERENCES unidad (id)
);

CREATE TABLE concepto (
    id VARCHAR(255) PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    id_tema VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_concepto_tema
        FOREIGN KEY (id_tema) REFERENCES tema (id)
);

CREATE TABLE pregunta (
    id VARCHAR(255) PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    id_concepto VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_pregunta_concepto
        FOREIGN KEY (id_concepto) REFERENCES concepto (id)
);

CREATE TABLE opciones (
    id VARCHAR(255) PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    es_correcta BOOLEAN NOT NULL,
    id_pregunta VARCHAR(255) NOT NULL,
    CONSTRAINT fk_opciones_pregunta
        FOREIGN KEY (id_pregunta) REFERENCES pregunta (id)
);

CREATE TABLE grupo (
    id VARCHAR(255) PRIMARY KEY,
    clave_grupo VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    semestre VARCHAR(255) NOT NULL,
    id_docente VARCHAR(255) NOT NULL,
    CONSTRAINT fk_grupo_docente
        FOREIGN KEY (id_docente) REFERENCES persona (id)
);

CREATE TABLE grupos_alumnos (
    id_grupo VARCHAR(255) NOT NULL,
    id_alumno VARCHAR(255) NOT NULL,
    PRIMARY KEY (id_grupo, id_alumno),
    CONSTRAINT fk_grupos_alumnos_grupo
        FOREIGN KEY (id_grupo) REFERENCES grupo (id),
    CONSTRAINT fk_grupos_alumnos_alumno
        FOREIGN KEY (id_alumno) REFERENCES persona (id)
);

CREATE TABLE quiz (
    id VARCHAR(255) PRIMARY KEY,
    detalles VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_finalizacion TIMESTAMP WITH TIME ZONE NOT NULL,
    id_grupo VARCHAR(255) NOT NULL,
    CONSTRAINT fk_quiz_grupo
        FOREIGN KEY (id_grupo) REFERENCES grupo (id)
);

CREATE TABLE quiz_x_pregunta (
    id VARCHAR(255) PRIMARY KEY,
    id_quiz VARCHAR(255) NOT NULL,
    id_pregunta VARCHAR(255) NOT NULL,
    CONSTRAINT uq_quiz_x_pregunta UNIQUE (id_quiz, id_pregunta),
    CONSTRAINT fk_quiz_x_pregunta_quiz
        FOREIGN KEY (id_quiz) REFERENCES quiz (id),
    CONSTRAINT fk_quiz_x_pregunta_pregunta
        FOREIGN KEY (id_pregunta) REFERENCES pregunta (id)
);

CREATE TABLE configuraciones (
    id VARCHAR(255) PRIMARY KEY,
    valor VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);